version: '3'
services:
  app:
    image: fastfood-api
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/fastfood
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - fastfood_network

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=fastfood
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - fastfood_data:/var/lib/postgresql/data
    networks:
      - fastfood_network

networks:
  fastfood_network:

volumes:
  fastfood_data:
