-- Initial schema for FastFood App

CREATE TABLE address (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city VARCHAR(100) NOT NULL,
    street VARCHAR(100) NOT NULL
);

CREATE TABLE branch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    address_id BIGINT UNIQUE,
    CONSTRAINT fk_branch_address FOREIGN KEY (address_id) REFERENCES address(id)
);

CREATE TABLE item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_type VARCHAR(31) NOT NULL,
    name VARCHAR(50) NOT NULL UNIQUE,
    name_es VARCHAR(50),
    icon VARCHAR(30),
    is_active BOOLEAN NOT NULL,
    price DOUBLE PRECISION,
    discount NUMERIC(2,1),
    version BIGINT
);

CREATE TABLE food_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT NOT NULL,
    creation_timestamp TIMESTAMP(6) NOT NULL,
    payment_timestamp TIMESTAMP(6),
    state VARCHAR(20),
    version BIGINT,
    CONSTRAINT fk_order_branch FOREIGN KEY (branch_id) REFERENCES branch(id)
);

CREATE TABLE food_order_detail (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity >= 1 AND quantity <= 99),
    historic_price DOUBLE PRECISION NOT NULL,
    CONSTRAINT fk_detail_item FOREIGN KEY (item_id) REFERENCES item(id)
);

CREATE TABLE food_order_food_order_details (
    food_order_id BIGINT NOT NULL,
    food_order_details_id BIGINT NOT NULL UNIQUE,
    CONSTRAINT fk_fo_fod_order FOREIGN KEY (food_order_id) REFERENCES food_order(id),
    CONSTRAINT fk_fo_fod_detail FOREIGN KEY (food_order_details_id) REFERENCES food_order_detail(id)
);

CREATE TABLE inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT NOT NULL,
    item_id BIGINT NOT NULL,
    stock_quantity INTEGER NOT NULL,
    is_available BOOLEAN NOT NULL,
    version BIGINT,
    UNIQUE (branch_id, item_id),
    CONSTRAINT fk_inventory_branch FOREIGN KEY (branch_id) REFERENCES branch(id),
    CONSTRAINT fk_inventory_item FOREIGN KEY (item_id) REFERENCES item(id)
);

CREATE TABLE menu_item (
    menu_id BIGINT NOT NULL,
    item_id BIGINT NOT NULL,
    CONSTRAINT fk_menu_item_menu FOREIGN KEY (menu_id) REFERENCES item(id),
    CONSTRAINT fk_menu_item_item FOREIGN KEY (item_id) REFERENCES item(id)
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL
);

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role VARCHAR(255),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users(id)
);
